adobe/helix-deploy

package-lock.json, package.json, src/action_builder.js, test/build.test.js
merges `template/index.js` and `main.js` into 1 bundle.
this allows to resolve the `node-fetch` imports properly.
=> Fix node fetch import

package-lock.json, package.json, src/template/index.js
currently, it's easiest to instrument epsagon in the adapter, since it already wraps the openwhisk action.
but, since we deploy the action `raw`, it no longer has (request) params to report:
we could try to create a new universal-adapter for epsagon or just ensure that the `__ow_query` params are also added as params (by fixing node-espagon diretctly)
=> feat(adapter): instrument epsagon

package-lock.json, package.json, src/template/index.js, test/aws.integration.js, test/build.test.js, test/fixtures/simple/index.js, test/gateway.integration.js, test/openwhisk.adapter.test.js, test/openwhisk.integration.js
fixes #48
rewrote parameter passing:
- all the params from `__ow_query` are appended to the `Request.url`
- all the params from `params` that don't match the _SECRET_ filter are appended to the `Request.url`
- added specific openwhisk adapter test
=> fix(wsk): invoke via API doesn't propagate params

package-lock.json, src/template/resolver.js, test/resolver.test.js
this is (currently) needed for invoking html actions via dispatch
=> fix(adapter): resolver should work with no version (for html actions)

src/deploy/AWSDeployer.js, src/deploy/OpenWhiskDeployer.js, src/gateway/FastlyGateway.js, test/gateway.integration.js
This changes all Gateway URLs as the package name is now the required first path segment.
BREAKING CHANGE: fixes #80 and breaks all Gateway URLs
=> fix(gateway): extract package name from URL instead of config

src/BaseConfig.js, src/deploy/AWSConfig.js, src/deploy/AWSDeployer.js, test/aws.deployer.test.js
=> feat(aws): add possibility to define lambda name format

src/gateway/FastlyGateway.js
Each service will now have an edge dictionary for backend priorities, so that we can shift traffic from one backend to another like this:
We can then establish an escalation protocol to shift traffic back and forth.
Fixes #112 
Rationale explained in https://github.com/adobe/helix-status/pull/284#issuecomment-780510463
> - adobe/helix-pages#695 would use the built-in health check of the html action, but only for spot checking and only as a last resort
> - adobe/helix-deploy#113 allows an operator to shift the entire traffic distribution to a different runtime after being alerted by New Relic and back once the issue has been resolved.
=> Dynamic Backend Priorities

src/template/aws-package-params.js, src/template/index.js, test/wrapper.test.js
=> fix(aws): ensure version in context.func is correct

src/gateway/FastlyGateway.js
our current logs include values like `helix-services/dispatch@v4?static.owner=adobe&static.repo=helix-pages&static.ref=everything-universal&static.root=` in the logs for `actionName`. This change cleans this up to `helix-services/dispatch@v4`
=> fix(logging): cleanup action name in logs

src/ActionBuilder.js, src/deploy/AWSConfig.js, src/deploy/AWSDeployer.js, test/aws.integration.js
fixes #128
adds 2 new features:
=> feat(aws): delete unused integrations

package-lock.json, package.json, src/template/index.js
fixes #147
needs: https://github.com/adobe/helix-epsagon/pull/171
---
this is a first version to enable epsagon tracing for AWS. since the lambda wrapper needs the epsagon token, we need to fetch the secrets first before invoking the wrapper. this has the only drawback, that we can't trace the fetch of the secrets. 
also see: #148
=> feat(uni): add espagon support for AWS

src/deploy/AWSDeployer.js, src/deploy/OpenWhiskDeployer.js, src/gateway/FastlyGateway.js
- feat(gateway): log the version lock header value
- fix(gateway): log status code as integer instead of string
- feat(gateway): trace aws and openwhisk transaction ids
We are now passing `x-cdn-request-id` into OW as `x-request-id` and into AWS as `x-amazn-trace-id`.
=> tune logging

src/ActionBuilder.js, src/gateway/FastlyGateway.js, src/template/resolver.js, test/fastly-gateway.test.js, test/fixtures/simple/index.js, test/gateway.integration.js, test/resolver.test.js
Implements #175 and adds a working resolution mechanism for Google: it will go back to Universal Runtime as there is no native way to create aliases for Google Cloud Functions.
The Fastly edge dictionary will be updated whenever a service ID and a token are provided (and `-l`), but a full update of the config will only be done if a checkpath has been provided, so that we can safely call `-l` for all our services, but keep the checkpath update to helix-pages.
=> Gateway aliases

src/template/index.js
=> fix(template): clean up x-error header value prior to sending response

src/gateway/FastlyGateway.js
Fixes two issues with the Google action lookup:
1. treat `?` as a version string terminator, so that the version lookup works even when you specify URL parameters
2. do not send a 302 for missing actions in Google, send a 404 instead like everyone else;
=> Fix Google Action Lookup

package-lock.json, package.json, src/Bundler.js
Adds support for the storage API provided by https://github.com/adobe/helix-universal/pull/29
- bump peer dependency
- install google storage client upon google deploy
=> add support for storage API

src/Bundler.js
this should reduce the generated bundle size substantially (from 3.7 MB to 1.4 MB JS for the simple action)
=> fix(bundler): exclude google storage dependency (included in Google Runtime)

src/ActionBuilder.js, src/BaseConfig.js, src/bundler/BaseBundler.js, src/template/validate-bundle.js, src/utils.js, test/build.test.js, test/deploy.test.js, test/fixtures/simple/index.js, test/fixtures/web-action/src/index.js
This PR improves the _validate bundle_ step by:
1. testing if there is a `lambda` adapter (instead of the openwhisk `main`)
2. invoking the adapter, if either `--test` or `--test-bundle` is given. if the response is not a 200, it fails (similar behaviour as if deployed and requested with `testUrl`)
fixes #353
=> feat: use lambda adapter to validate bundle and execute it

src/cli.js, src/deploy/AWSConfig.js, src/deploy/AWSDeployer.js, test/aws.integration.js, test/fixtures/simple-authorizer/index.js, test/fixtures/simple-authorizer/package.json
adds 2 new options that come in effect when _linking_
`--aws-create-authorizer = my-authorizer_${version}` 
This is specified when deploying the authorizer function and creates authorizers in the API gateway.
It also adds the required invoke permission to the function alias.
this fixes #261 
`--aws-attach-authorizer = my-authorizer_v1`
This is specified when _linking_ a function. the specified authorizer will be attached to the linked routes.
this fixes #260
=> feat: add AWS lambda authorizers support

src/DevelopmentServer.js, test/fixtures/server-test/package.json, test/fixtures/server-test/test-dev.env, test/fixtures/server-test/test-package.env, test/fixtures/server-test/test.env, test/server.test.js
fix the params loading:
- package file-params
- package params
- file-param
- params
- dev file-params
- dev-params
the later wins over the earlier. 
example `wsk` in `package.json`:
```json
"wsk": {
"params-file": [
"test.env"
],
"params": {
"TEST_PARAM": "foo-param",
"TEST_DEFAULT_PARAM": "default"
},
"package": {
"name": "simple-package",
"params": {
"TEST_PACKAGE_PARAM": "foo-package-param"
},
"params-file": [
"test-package.env"
]
},
"dev": {
"params": {
"TEST_DEV_PARAM": "foo-dev-param",
"TEST_DEFAULT_PARAM": "dev-default"
},
"params-file": [
"test-dev.env"
]
}
```
=> fix: fix development server dev params

src/gateway/FastlyGateway.js, test/aws.integration.js
The token dictionary has the tendency of overflowing. This PR catches the
error that occurs when the token dictionary can no longer be updated because
it has too many entries, then gets all tokens that have exceeded their validity
and the ten oldest tokens and deletes them from the dictionary before trying
again. This fixes the issue.
- refactor(gateway): log dictionary size
- fix(gateway): clean up old and outdated tokens when token dictionary is full
- test: run all tests again
=> Cleanup Token Dictionary

src/deploy/AWSConfig.js, src/deploy/AWSDeployer.js, test/cli.test.js
fix #243
Uses template bucket `helix-deploy-template` by default, logs a warning if not found but continues working.
=> fix: add tags to newly created polyfunc bucket

test/fastly-gateway.test.js
somehow the gateway tests, create a VLC version that uses openwhisk as backend, which then fails and alerts the monitors.
=> chore: disable gateway tests

src/DevelopmentServer.js, test/server.test.js
... which can then be used in log statements, even when using `$ npm run start` with `nodemon`
=> feat: support invocation id

src/deploy/ComputeAtEdgeDeployer.js
And properly close it after updatePackage.
This fixes a 5-minute hang that happens after deployment.
Fixes: #587
Every time I run hedy to deploy something to Fastly c@e I have to check when it's finished and then press Ctrl-C to get my command prompt back, unless I wait 5 minutes. That's clearly not ideal.
It has been tested with Fastly Compute@Edge.
=> fix(fastly) Close fastly client after deploy

src/bundler/WebpackBundler.js
=> fix: exclude @aws-sdk and its descendants

package-lock.json, src/deploy/CloudflareDeployer.js
The path to the Javascript file to be deployed was made relative to a directory different than the current directory, which cause the file read to fail. The path is already absolute so we don't need to process it.
Fixes: #619
It makes a failure scenario of deploying to Cloudflare work.
It has been tested by making real deployments to Cloudflare Workers.
=> fix(cloudflare): Do not make absolute path relative

src/deploy/ComputeAtEdgeDeployer.js
We've been plagued by build failures in https://app.circleci.com/pipelines/github/adobe/helix-rum-collector?branch=renovate-adobe-fixes
due to a failed resolution of the `js-compute-runtime-cli.js` file.
The resolution would work in tests here, because `hedy` was the only dependency, and it would also work in projects that had a conflicting
version of `@fastly/js-compute` installed (because `npm install` would then keep one copy right below `node_modules/@adobe/helix-deploy/node_modules`)
But in scenarios where there was a clean install, `js-compute` would be underneath `node_modules/@fastly/js-compute` and our `ComputeAtEdgeDeployer` would
unsuccessfully try to load the script from its own `node_modules`.
Instead of trying to build a fallback mechanism, the fix in this PR will import the …
=> fix(fastly): do not fork the process, instead use fastly's own CLI backend

src/deploy/ComputeAtEdgeDeployer.js
when no `--fastly-gateway` parameter has been set, then deploying to Fastly Compute fails
```
--: uploading package to fastly, service version 5
--: creating secrets dictionary
--: updating gateway backend:
error: Fastly Compute@Edge - Address 'address' is not a valid IPv4, IPv6 or hostname
error: aborted due to errors during deploy
```
this is caused by a server-side validation on the fastly end. The fix will make sure host
is set before trying to update the gateway host.
=> fix(fastly): guard against missing gateway name

src/bundler/WebpackBundler.js
This is a fairly simple extension point that depends upon a statically named file hlx.webpack.customize.js. This is expected to export a function named extraPlugins that accepts the hedy config and the webpack config and returns an array of plugins.
This is an alternative to #642 which provides a narrower extension point.
#641 
There are challenges with using opentelemetry-js and webpack-bundled modules. It is possible to work around these challenges using a webpack plugin but doing so with hedy is not possible today.
I've applied this patch to a local project.
=> feat: allow addition of webpack plugins. fixes #641

src/DevelopmentServer.js, test/server.test.js
noticed that when I tested the discover API endpoint with a path such as:
```
localhost:3000/discover/?url=https://some.sharepoint.com/_layouts/15/Doc.aspx?sourcedoc=%7B44CE4215-3123-434B-9648-D1EC8007B1B7%7D&file=this-is-the-file-name.docx&action=default&mobileredirect=true'
```
I only see everything up to `.../Doc.aspx` because it splits at the second `?`
=> fix: do not stop query string at question mark

src/bundler/WebpackBundler.js
add `import` as condition for packages that exports conditionally, eg:
https://github.com/frenchbread/private-ip/blob/9d984ed3cd6d17d1d5a0f0d358c13c4c7a8996dd/package.json#L5-L10
=> fix: add 'import' condition for package imports

README.md, src/deploy/AWSConfig.js, src/deploy/AWSDeployer.js, test/aws.deployer.test.js, test/cli.test.js
Add an `--aws-tags` option to the CLI. This is an array of key value pairs, delimited by `=` (similar to the AWS CLI).
#651 
Primarily need this for cost tracking at scale.
Manual testing. Added some unit tests to cover the configuration cases as well.
=> feat: add support for custom AWS tags which are set on the deployed Lambda. Fixes #651

src/bundler/WebpackBundler.js, test/build.test.js
- remove `condtionNames` from webpack bundler to make the module imports more stable
- switch to `production` mode so that packages that export different sources depending on the development/production mode use the production code (for example https://github.com/micromark/micromark/blob/8b08d16891f4d6801eb0c0e990bd7b87836c0826/packages/micromark-core-commonmark/package.json#L36-L39)
- disable minimize and keep named module ids for easier debugging
=> fix: remove condition names

README.md, src/deploy/AWSConfig.js, src/deploy/AWSDeployer.js
When setting up Lambda functions that are triggered based on an SNS subscription, _if_ the subscription is tied to a specific function alias, the permission needs to be granted on the alias. This change allows for such permissions to be deployed through hedy.
I have a function that receives SNS messages on a specific alias (prod) and NOT $LATEST.
I've used this commit to deploy and successfully sent SNS messages to the correct aliased version.
> Note - I originally committed this as a 'fix' but on reconsideration, it's really a 'feat'.
=> feat(aws): allow extra permissions to optionally include an alias

src/deploy/AWSDeployer.js
AWS Lambda not ready for updates
Increase timeout via additional retries and backoff for checks for Lambda to be ready
#727
Deploys were failing due to the Lambda not being ready before the next step executed
- Reproducing failing deploy locally
- Making updates and linking this library
- Re-attempting the same deploy
=> fix: AWS Lambda not ready for updates fixes #727

package-lock.json, src/deploy/AWSDeployer.js, test/aws.deployer.test.js
Fixes #734. Always set `Layers` to an array, even if `awsLayers` is not configured.
Manually verified that setting an empty `Layers` array on Lambda will overwrite and remove any previously set layers.
Added 3 new unit tests for cases
- no `awsLayers` set
- `awsLayers` with 1 layer
- `awsLayers` with 2 layers
=> fix: Removing awsLayers does not remove layers from a deployed function

package-lock.json, package.json, src/BaseConfig.js, src/bundler/ESBuildBundler.js, src/cli.js
currently adds `esbuild` as dependency, not sure whether there's another mechanism to not inflate `helix-deploy`s dependency list.
=> feat: support `esbuild` as alternative bundler

src/bundler/ESBuildBundler.js, src/template/node-index.mjs, test/build.test.js, test/setup-env.js
=> fix(esbuild): avoid using `createRequire` as import name
