- src/DevelopmentServer.js
- src/action_builder.js
- src/cli.js
- src/deploy/AWSDeployer.js
- test/cli.test.js
- test/deploy.test.js
> Selective deploy

- src/action_builder.js
- src/cli.js
- src/deploy/AWSDeployer.js
> feat(aws): reuse existing api and integration

- package-lock.json
- package.json
- src/deploy/AWSDeployer.js
- src/deploy/OpenWhiskDeployer.js
- src/template/index.js
- test/aws.integration.js
> feat(aws): add secrets from parameter store at runtime

- package-lock.json
- src/cli.js
- src/config/adobeioruntime-node10.js
- src/deploy/AWSDeployer.js
- src/deploy/AzureDeployer.js
- src/deploy/BaseDeployer.js
- src/deploy/OpenWhiskDeployer.js
- src/template/index.js
- test/aws.integration.js
- test/build.test.js
- test/fixtures/simple/package.json
various fixes:
- include suffix / __ow_path in context  (see #17)
- add route for requests with suffix (see #13)
- allow each deployer to specify test (see #10)
- dependency list not valid tag value (see #12)
> Improvements

- src/action_builder.js
- src/cli.js
- src/deploy/AWSDeployer.js
- src/deploy/AzureDeployer.js
- src/deploy/BaseDeployer.js
- src/deploy/OpenWhiskDeployer.js
- test/build.test.js
- test/cli.test.js
- test/deploy.test.js
> feat(cli): improve deployer selection

- src/deploy/AWSDeployer.js
> fix(aws): use hash function to generate consistent statement ids

- test/aws.integration.js
fixes #29 and the build error on `main`
> New lambda role

- src/action_builder.js
- src/cli.js
- src/deploy/AWSDeployer.js
- src/deploy/BaseDeployer.js
- src/deploy/OpenWhiskDeployer.js
- test/build.test.js
- test/deploy.test.js
> feat(aws): add command to delete stray buckets

- src/deploy/AWSDeployer.js
- src/deploy/BaseDeployer.js
- test/deploy.test.js
> fix(aws): retry test for 404

- src/config/adobeioruntime-node10.js
- src/template/index.js
> fix(aws): fetch all parameters

- src/ActionBuilder.js
- src/deploy/AWSDeployer.js
- src/deploy/BaseDeployer.js
- test/deploy.test.js
> Various Fixes

- src/template/index.js
- src/template/utils.js
- test/adapter-utils.test.js
> feat(adapter): add charset=utf-8 if missing

- src/ActionBuilder.js
- src/BaseConfig.js
- src/deploy/AWSDeployer.js
- src/deploy/OpenWhiskDeployer.js
- test/action-builder.test.js
- test/deploy.test.js
> feat(builder): add support for formats and properties

- src/deploy/BaseDeployer.js
> fix: use correct cache option

- src/gateway/FastlyGateway.js
- test/fixtures/simple/index.js
- test/gateway.integration.js
- test/openwhisk.integration.js
> Carry surrogates

- src/template/index.js
needs for coralogix logger in AWS
> feat(log): flush log in AWS if present

- src/deploy/GoogleDeployer.js
> fix(google): do not enable google deployer if project id has not been specified

- package-lock.json
- package.json
- src/template/index.js
- test/wrapper.test.js
we can use this as a template for other wrapper unit tests
fixes #121
> test(azure): add simple wrapper test

- src/gateway/FastlyConfig.js
- src/gateway/FastlyGateway.js
- test/gateway.integration.js
> Log to Coralogix

- src/template/index.js
- test/wrapper.test.js
> fix(openwhisk): convert base64 encoded json request bodies into strings

- src/gateway/FastlyGateway.js
- test/fixtures/simple/index.js
Adds a retry facility for idempotempt requests that show intermittent errors.
fixes #152
> Restart 503 and 504 responses

- src/template/index.js
- test/wrapper.test.js
> fix(adapter): handle illegal request header errors with 400

- src/gateway/FastlyGateway.js
- src/template/index.js
- test/openwhisk.adapter.test.js
- feat(gateway): log x-error header
- feat(template): set x-error header for caught 500s
> x error header

- package-lock.json
- package.json
- src/template/index.js
- test/wrapper-epsagon.test.js
> Disable epsagon for status pings

- src/template/aws-package-params.js
> feat(aws): cache package parameters

- src/deploy/GoogleDeployer.js
- test/gateway.integration.js
- test/google.integration.js
> Re-enable google

- src/gateway/FastlyGateway.js
> fix(gateway): prevent duplication of @ in version links

- src/ActionBuilder.js
- src/deploy/OpenWhiskDeployer.js
- test/deploy.test.js
- test/fixtures/simple/package.json
> fix(build): don't check wsk namespace for non-deploy

- src/template/utils.js
- test/adapter-utils.test.js
> feat(adapter): log better errors for missing headers

- src/template/index.d.ts
- src/template/index.js
- test/aws.adapter.test.js
- test/azure.adapter.test.js
- test/google.adapter.test.js
- test/openwhisk.adapter.test.js
> feat(adapter): add consistent tracing information

- src/template/index.js
- test/openwhisk.adapter.test.js
> fix(ow): correctly decompose the function name

- src/ActionBuilder.js
- src/deploy/AzureDeployer.js
- src/deploy/BaseDeployer.js
- src/deploy/GoogleDeployer.js
use common fetch context and reset after using deployer.
> fix(deploy): try to reset all fetch context to avoid hanging processes

- package.json
- src/deploy/GoogleDeployer.js
> fix(google): avoid dots in package name for secrets

- src/gateway/FastlyGateway.js
reduce check frequency 10-fold
We could also add an option for the interval, but that would be a bigger change.
> fix(gateway): increase check interval

- src/gateway/FastlyConfig.js
- src/gateway/FastlyGateway.js
- test/gateway.integration.js
> feat(gateway): enable configurable check interval

- src/gateway/FastlyGateway.js
see https://app.circleci.com/pipelines/github/adobe/helix-pages/4995/workflows/676db75b-f1f2-4b8a-800b-fca54d1cbaab/jobs/22916
> fix(gateway): do not select a healthcheck if the interval is zero (disabled)

- src/deploy/AWSDeployer.js
Creates or updates aliases for a Lambda _function version_ (which is an incremental version number) when `deploy-sequences` is run.
E.g. for Lambda `helix-observation--index-files`, which is at incremental version `62` and package version `4.0.1`, it would create or update aliases named `latest`, `v4` and `v4_0`, which all then point to incremental version `62`. All existing EventBridge rules and SQS triggers that are bound to one of those function aliases will then automatically invoke version `62`.
> feat: add aliases for function in updateLinks

- src/deploy/AWSConfig.js
- src/deploy/AWSDeployer.js
it turns out that it would be useful to disable the `secrets manager` for helix-pages....
> feat: add options to select params manager

- src/deploy/AWSDeployer.js
> fix: wait for aws states completed between deploy steps

- src/cli.js
- test/cli.test.js
adds the ability to make a parameter as important.
> fix: add option to override env

- src/deploy/AWSDeployer.js
- test/aws.integration.js
> fix(aws): link integration to v alias of function

- src/deploy/AWSDeployer.js
- test/aws.integration.js
> fix: update links should link route to alias, not specific version

- src/deploy/AWSConfig.js
- src/deploy/AWSDeployer.js
- test/cli.test.js
> feat: add support to specify architecture

- package-lock.json
- package.json
- src/deploy/AWSConfig.js
- src/deploy/AWSDeployer.js
- test/cli.test.js
> feat: use static deploy bucket

- src/template/aws-function-proxy.js
Code to be used for deploy-proxy function, as module for node 18
> fix: use module type code for deploy proxy

- src/template/cloudflare-adapter.js
Fixing a mistake which could have been prevented using typescript
> fix(cloudflare): retrieving path from URL created a NPE

- src/deploy/GoogleDeployer.js
Even though I haven't configured any google credential, I'm getting the following failure:
```
$ node ../helix-deploy/src/index.js --aws-cleanup-versions --cleanup-patch=1w --no-build --name helix3/indexer
./node_modules/@google-cloud/functions/build/src/v1/cloud_functions_service_client.js:254
throw err;
^
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
at GoogleAuth.getApplicationDefaultAsync (./node_modules/google-auth-library/build/src/auth/googleauth.js:271:15)
```
> fix: assert deployer is ready before invoking

- src/template/polyfills/fetch.js
Adding Headers to polyfill file thus @adobe/fetch.Headers can be used in the code
https://github.com/adobe/helix-deploy/issues/698
Improve support of @adobe/fetch
Deployment on Universal Editor Service
> feat(cloudflare, fastly): adding Headers to polyfill

- README.md
- package-lock.json
- src/deploy/AWSConfig.js
- src/deploy/AWSDeployer.js
- test/aws.deployer.test.js
- test/cli.test.js
This adds a new `--aws-handler` argument that if set will be used for the `Handler` config of the AWS Lambda function.
```
--aws-handler  Set custom lambda Handler. For example, set if an AWS layer provides another function
entry point.                                                                  [string]
```
For instrumenting our Lambdas with New Relic using [their layer approach](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/instrument-your-own/) it is necessary to configure a different `Handler` on the Lambda function.
This is because the New Relic layer adds a "wrapper" handler for instrumentation purposes. This handler is called `newrelic-lambda-wrapper.handler`. Internally that will call the "actual" lambda code by …
> feat(aws): support configuring Lambda Handler

- package-lock.json
- src/deploy/AWSConfig.js
- src/deploy/AWSDeployer.js
- test/aws.deployer.test.js
> feat: add regional deploy buckets

- src/BaseConfig.js
- test/cli.test.js
node version 20 has been put into maintenance mode: https://nodejs.org/en/about/previous-releases
> fix: change default node version to 22

- .github/workflows/main.yaml
- test/aws.deployer.test.js
- test/aws.integration.js
and use a repository secret to store the AWS role instead
> chore(test): completely get rid of account id
